trigger:
 branches:
   include:
   - master

stages:
- stage: Build

  jobs:  

  - job: Build
    displayName: "Build app and installer"
    pool:
      vmImage: 'windows-latest'

    steps:

    - task: VSBuild@1
      inputs:
        solution: 'TestApp.sln'
        vsVersion: 'latest'
        platform: 'x64'
        configuration: 'Release'
        msbuildArchitecture: 'x64'
        msbuildArgs: '/t:Restore /p:RuntimeIdentifier=win-x64'

    - task: VSBuild@1
      inputs:
        solution: 'TestApp.sln'
        vsVersion: 'latest'
        platform: 'x64'
        configuration: 'Release' 
        msbuildArchitecture: 'x64'
        msbuildArgs: ''
